# Generated by Django 5.1.15 on 2026-09-11 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eaten_at', models.DateTimeField(verbose_name='Время приёма')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус'), ('impulsive', 'Импульсивный')], max_length=20)),
                ('is_planned', models.BooleanField(default=True, verbose_name='Плановый')),
                ('reasons', models.JSONField(blank=True, default=list, help_text='До 2 значений из Reason')),
                ('hunger_level', models.CharField(blank=True, choices=[('slightly', 'Слегка голоден'), ('hungry', 'Голоден'), ('very', 'Очень голоден')], max_length=20, null=True)),
                ('portion', models.CharField(choices=[('small', 'Маленькая'), ('moderate', 'Умеренная'), ('large', 'Большая')], max_length=20)),
                ('junk_items', models.JSONField(blank=True, default=list)),
                ('positive_items', models.JSONField(blank=True, default=list)),
                ('rating', models.CharField(choices=[('good', 'Хорошо'), ('normal', 'Нормально'), ('bad', 'Плохо')], max_length=20)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-eaten_at'],
                'indexes': [models.Index(fields=['user', 'eaten_at'], name='food_tracke_user_id_c5cec8_idx')],
            },
        ),
    ]
