# Generated by Django 4.2.30 on 2026-06-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('blank_id', models.AutoField(primary_key=True, serialize=False)),
                ('blank_filename_original', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('blank_file', models.FileField(blank=True, null=True, upload_to='blanks/', verbose_name='Файл бланка')),
                ('ts_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('img_index', models.CharField(blank=True, max_length=1, verbose_name='Индекс столбца фото')),
                ('color_index', models.CharField(blank=True, max_length=1, verbose_name='Индекс столбца цвета')),
                ('size_index', models.CharField(blank=True, max_length=1, verbose_name='Индекс столбца размера')),
                ('amount_index', models.CharField(blank=True, max_length=1, verbose_name='Индекс столбца количества')),
                ('price_index', models.CharField(blank=True, max_length=1, verbose_name='Индекс столбца цены')),
                ('link_index', models.CharField(blank=True, max_length=1, verbose_name='Индекс столбца ссылки')),
                ('caption_row_index', models.IntegerField(default=0, verbose_name='Строка заголовка')),
                ('target_sheet_name', models.CharField(blank=True, max_length=255, verbose_name='Имя листа')),
            ],
            options={
                'verbose_name': 'Бланк',
                'verbose_name_plural': 'Бланки',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Список 1', max_length=255, verbose_name='Название')),
                ('ts_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=2000, verbose_name='Ссылка на товар')),
                ('img_url', models.URLField(blank=True, max_length=2000, verbose_name='URL изображения')),
                ('color', models.CharField(blank=True, max_length=255, verbose_name='Цвет')),
                ('size', models.CharField(blank=True, max_length=255, verbose_name='Размер')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('shop_home_page', models.URLField(blank=True, max_length=2000, verbose_name='Страница магазина')),
                ('cart_order', models.IntegerField(default=0, verbose_name='Порядок в корзине')),
                ('deleted', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.cart')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
